### PR TITLE
add JET.jl workshop

### PR DESCRIPTION
**Pull request by aviatesk**
Since I'd like to do some live coding with MacroTools.jl, I ended up adding it as submodule.

It might be problematic, because then we can't instantiate this project without `git sudmodule init && git submodule update` (because JET depends on MacroTools.jl).
I of course added the instructions, but we may want to remove it entirely, and just let users to `dev` it MacroTools.jl.

### CODE REVIEW

**Comment by timholy** [comment]
I want to do a Flux demo too, that's funny.

Why can we just add Flux & FluxML to the Project.toml, pinned to a specific version?

**Comment by aviatesk** [comment]
`dev` will try to pull the latest commit, so I wondered we lose the reproducibility in the future, but that should be enough at least for our workshop.
But I think submodules can be really problematic after all, so I'm going with your suggestion.

**Comment by timholy** [comment]
`PackageSpec` allows you to specify a git commit SHA1, maybe we can use that?

**Review by timholy — APPROVED** [review]
I've skimmed it. I think it's solid; the only concern might be some degree of complexity, especially with the metaprogramming examples, but there's always a tradeoff between realism and comprehensibility. I think it works as-is.

I'm looking forward to it, especially the live-coding part!

**Comment by aviatesk** [comment]
Thanks for your review !

As for package development stuff, `Pkg.dev` actually doesn't allow us to checkout to a specific git commit SHA1,
and on Slack I got a recommendation of manual checkout.

This is what I included within a notebook:
```julia
using Pkg

Pkg.develop("MacroTools")

let back = pwd()
    try 
        path = Base.find_package("MacroTools")
        cd(dirname(dirname(path)))
        run(`git checkout -b juliacon fef1c6fab11f30d6ae1c1fff6c42be49ccef5d10`)
    catch err
        @warn "please manually checkout to fef1c6fab11f30d6ae1c1fff6c42be49ccef5d10"
        throw(err)
    finally
        cd(back)
    end
end
```

**Pull request merged**
